setwd('C:/Users/uwmly/Desktop/CE-CERT/CARTEEH')
library(dplyr)
od = read.csv('la_lb_rv_od.csv')
ca_block = read.csv('tl_2017_06_tabblock10.dbf.csv')
od = od %>% select(w_geocode,h_geocode,S000,bg)
od$w_geocode = as.character(od$w_geocode)
od$h_geocode = as.character(od$h_geocode)
ca_block$GEOID10 = as.character(ca_block$GEOID10)
ca_block = ca_block %>% select(GEOID10,INTPTLAT10,INTPTLON10)

commute = left_join(od,ca_block,by = c("h_geocode"="GEOID10"))
names(commute) = c('work','home','num_of_workers','BG','origin_lat','origin_lon')

commute = left_join(commute,ca_block,by=c("work" = "GEOID10"))
names(commute) = c('work','home','num_of_workers','BG','origin_lat','origin_lon','dest_lat','dest_lon')
write.csv(commute,'commute.csv',row.names = F)
write.csv(commute[which(commute$BG == 60375436011),],'commute1.csv',row.names = F)
write.csv(commute[which(commute$BG == 60650301043),],'commute2.csv',row.names = F)
write.csv(commute[which(commute$BG == 60372060101),],'commute3.csv',row.names = F)
